# Generated by Django 5.0.4 on 2024-05-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_create_date_reviewrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
