# Generated by Django 5.0.4 on 2024-05-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_2',
            new_name='address_line_2',
        ),
    ]
